<?php

namespace app\apiadmin\controller\coupon;

use app\apiadmin\controller\Base;
use app\apiadmin\validate\CouponCategoryValidate;
use app\common\model\coupon\CouponCategoryModel;
use app\common\logic\HandleLogic;

class CouponCategory extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if ($this->admin_user['identity'] != 1){
            echo json_encode(['status'=>'0','code'=>"10000",'msg'=>'没权限']);die;
        }
    }

    public function handle($act='')
    {
        $handleLogic = new HandleLogic;
        $validate = new CouponCategoryValidate;
        $arr = array_return();
        $validate_result = $validate->scene($act)->check($this->param);
        if (!$validate_result) {
            $arr['status'] = 0;
            $arr['msg'] = $validate->getError();
            goto error;
        }
        $arr = $handleLogic->Handle($this->param,'app\common\model\coupon\CouponCategoryModel',$act);
        error:
        return return_json($arr);
    }

    public function lists(CouponCategoryModel $model)
    {
        $arr = array_return();
        $response = [
            'lists' => array()
        ];
        $lists = $model->scope('where', $this->param)->select();
        $response['lists'] = $lists;
        $arr['data'] = $response;
        return return_json($arr);
    }

    public function add()
    {
        return $this->handle('add');
    }

    public function edit()
    {
        return $this->handle('edit');
    }

    public function del()
    {
        return $this->handle('del');
    }
}
