<?php

namespace app\apiadmin\controller\coupon;

use app\apiadmin\controller\Base;
use app\common\validate\CouponValidate;
use app\common\model\coupon\CouponModel;
use app\apiadmin\logic\coupon\CouponIssueLogic;
use sakuno\utils\JsonUtils;

class CouponIssue extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if ($this->admin_user['identity'] != 1) {
            echo json_encode(['status' => '0', 'code' => "10000", 'msg' => '没权限']);
            die;
        }
    }

    /**
     * 优惠券发行列表
     * @param cate_model $model
     * @return \think\response\Json
     */
    public function lists(CouponIssueLogic $logic)
    {
        $this->param['field'] = 'id,coupon_name,uid,coupon_price,use_min_price,start_time,end_time,receive,status';
        $page                 = isset($this->param['page']) ? $this->param['page'] : 1;
        $lists                = $logic->getIssueList($page, $this->admin['list_rows'], $this->param);
        $data                 = ['lists' => $lists];
        return JsonUtils::successful('获取成功', $data);
    }
}