<?php

namespace app\apiadmin\controller\coupon;

use app\apiadmin\controller\Base;
use app\common\validate\CouponValidate;
use app\common\model\coupon\CouponModel;
use app\apiadmin\logic\coupon\CouponLogic;
use sakuno\utils\JsonUtils;

class Coupon extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if ($this->admin_user['identity'] != 1) {
            echo json_encode(['status' => '0', 'code' => "10000", 'msg' => '没权限']);
            die;
        }
    }

    /**
     * 优惠券列表
     * @param cate_model $model
     * @return \think\response\Json
     */
    public function lists(CouponLogic $logic)
    {
        $this->param['field'] = 'id,title,use_min_price,used,issued,add_time';
        $page                 = isset($this->param['page']) ? $this->param['page'] : 1;
        $lists                = $logic->getCouponList($page, $this->admin['list_rows'], $this->param);
        $data                 = ['lists' => $lists];
        return JsonUtils::successful('获取成功', $data);
    }

    /**
     * 优惠券操作
     * @param string $act
     * @return \think\Response|\think\response\Json
     */
    public function couponHandle($act='')
    {
        $couponLogic = new CouponLogic();
        $validate = new CouponValidate();
        $validate_result = $validate->scene($act)->check($this->param);
        if (!$validate_result) {
            return JsonUtils::fail($validate->getError());
        }
        $arr = $couponLogic->couponHandel($this->param);
        return return_json($arr);
    }

    public function add()
    {
        return $this->couponHandle('add');
    }

    public function edit()
    {
        return $this->couponHandle('edit');
    }

    public function info(CouponModel $model)
    {
        $validate = new CouponValidate();
        $validate_result = $validate->scene('info')->check($this->param);
        if (!$validate_result) {
            return JsonUtils::fail($validate->getError());
        }
        return $model->getInfo($this->param);
    }

    public function del(CouponLogic $logic)
    {
        $coupon_id = $this->param['id'] ?? 0;
        if (empty($coupon_id)){
            return JsonUtils::fail( 'coupon_id不能为空');
        };
        return $logic->delCoupon($coupon_id);
    }
}
